apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: sethsacher/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      # Watch these file types
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .
    - image: sethsacher/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
    - image: sethsacher/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
# Use this yml for the deployment
# These are deleted when you close down. Exclude persistent
# drives (like a DB) to avoid losing data.
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/client-cluster-ip-service.yml
      - k8s/server-cluster-ip-service.yml
